/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-05-14 03:07:32 UTC)
 * on 2013-05-16 at 07:43:41 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.data;

/**
 * Service definition for Data (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link DataRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Data extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION == 14,
        "You are currently running with version %s of google-api-client. " +
        "You need version 1.14 of google-api-client to run version " +
        "1.14.2-beta of the  library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://alvar-mbass.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "data/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Data(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Data(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "retrieveAllDistrict".
   *
   * This request holds the parameters needed by the the data server.  After setting any optional
   * parameters, call the {@link RetrieveAllDistrict#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public RetrieveAllDistrict retrieveAllDistrict() throws java.io.IOException {
    RetrieveAllDistrict result = new RetrieveAllDistrict();
    initialize(result);
    return result;
  }

  public class RetrieveAllDistrict extends DataRequest<com.google.api.services.data.model.GcDistrictCollection> {

    private static final String REST_PATH = "retrieveAllDistrict";

    /**
     * Create a request for the method "retrieveAllDistrict".
     *
     * This request holds the parameters needed by the the data server.  After setting any optional
     * parameters, call the {@link RetrieveAllDistrict#execute()} method to invoke the remote
     * operation. <p> {@link RetrieveAllDistrict#initialize(com.google.api.client.googleapis.services.
     * AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected RetrieveAllDistrict() {
      super(Data.this, "POST", REST_PATH, null, com.google.api.services.data.model.GcDistrictCollection.class);
    }

    @Override
    public RetrieveAllDistrict setAlt(java.lang.String alt) {
      return (RetrieveAllDistrict) super.setAlt(alt);
    }

    @Override
    public RetrieveAllDistrict setFields(java.lang.String fields) {
      return (RetrieveAllDistrict) super.setFields(fields);
    }

    @Override
    public RetrieveAllDistrict setKey(java.lang.String key) {
      return (RetrieveAllDistrict) super.setKey(key);
    }

    @Override
    public RetrieveAllDistrict setOauthToken(java.lang.String oauthToken) {
      return (RetrieveAllDistrict) super.setOauthToken(oauthToken);
    }

    @Override
    public RetrieveAllDistrict setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RetrieveAllDistrict) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RetrieveAllDistrict setQuotaUser(java.lang.String quotaUser) {
      return (RetrieveAllDistrict) super.setQuotaUser(quotaUser);
    }

    @Override
    public RetrieveAllDistrict setUserIp(java.lang.String userIp) {
      return (RetrieveAllDistrict) super.setUserIp(userIp);
    }

    @Override
    public RetrieveAllDistrict set(String parameterName, Object value) {
      return (RetrieveAllDistrict) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "retrieveAllParty".
   *
   * This request holds the parameters needed by the the data server.  After setting any optional
   * parameters, call the {@link RetrieveAllParty#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public RetrieveAllParty retrieveAllParty() throws java.io.IOException {
    RetrieveAllParty result = new RetrieveAllParty();
    initialize(result);
    return result;
  }

  public class RetrieveAllParty extends DataRequest<com.google.api.services.data.model.PartyCollection> {

    private static final String REST_PATH = "retrieveAllParty";

    /**
     * Create a request for the method "retrieveAllParty".
     *
     * This request holds the parameters needed by the the data server.  After setting any optional
     * parameters, call the {@link RetrieveAllParty#execute()} method to invoke the remote operation.
     * <p> {@link RetrieveAllParty#initialize(com.google.api.client.googleapis.services.AbstractGoogle
     * ClientRequest)} must be called to initialize this instance immediately after invoking the
     * constructor. </p>
     *
     * @since 1.13
     */
    protected RetrieveAllParty() {
      super(Data.this, "POST", REST_PATH, null, com.google.api.services.data.model.PartyCollection.class);
    }

    @Override
    public RetrieveAllParty setAlt(java.lang.String alt) {
      return (RetrieveAllParty) super.setAlt(alt);
    }

    @Override
    public RetrieveAllParty setFields(java.lang.String fields) {
      return (RetrieveAllParty) super.setFields(fields);
    }

    @Override
    public RetrieveAllParty setKey(java.lang.String key) {
      return (RetrieveAllParty) super.setKey(key);
    }

    @Override
    public RetrieveAllParty setOauthToken(java.lang.String oauthToken) {
      return (RetrieveAllParty) super.setOauthToken(oauthToken);
    }

    @Override
    public RetrieveAllParty setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RetrieveAllParty) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RetrieveAllParty setQuotaUser(java.lang.String quotaUser) {
      return (RetrieveAllParty) super.setQuotaUser(quotaUser);
    }

    @Override
    public RetrieveAllParty setUserIp(java.lang.String userIp) {
      return (RetrieveAllParty) super.setUserIp(userIp);
    }

    @Override
    public RetrieveAllParty set(String parameterName, Object value) {
      return (RetrieveAllParty) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "retrieveCandidateList".
   *
   * This request holds the parameters needed by the the data server.  After setting any optional
   * parameters, call the {@link RetrieveCandidateList#execute()} method to invoke the remote
   * operation.
   *
   * @param gcId
   * @return the request
   */
  public RetrieveCandidateList retrieveCandidateList(java.lang.Long gcId) throws java.io.IOException {
    RetrieveCandidateList result = new RetrieveCandidateList(gcId);
    initialize(result);
    return result;
  }

  public class RetrieveCandidateList extends DataRequest<com.google.api.services.data.model.CandidateListCollection> {

    private static final String REST_PATH = "retrieveCandidateList/{gcId}";

    /**
     * Create a request for the method "retrieveCandidateList".
     *
     * This request holds the parameters needed by the the data server.  After setting any optional
     * parameters, call the {@link RetrieveCandidateList#execute()} method to invoke the remote
     * operation. <p> {@link RetrieveCandidateList#initialize(com.google.api.client.googleapis.service
     * s.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param gcId
     * @since 1.13
     */
    protected RetrieveCandidateList(java.lang.Long gcId) {
      super(Data.this, "POST", REST_PATH, null, com.google.api.services.data.model.CandidateListCollection.class);
      this.gcId = com.google.api.client.util.Preconditions.checkNotNull(gcId, "Required parameter gcId must be specified.");
    }

    @Override
    public RetrieveCandidateList setAlt(java.lang.String alt) {
      return (RetrieveCandidateList) super.setAlt(alt);
    }

    @Override
    public RetrieveCandidateList setFields(java.lang.String fields) {
      return (RetrieveCandidateList) super.setFields(fields);
    }

    @Override
    public RetrieveCandidateList setKey(java.lang.String key) {
      return (RetrieveCandidateList) super.setKey(key);
    }

    @Override
    public RetrieveCandidateList setOauthToken(java.lang.String oauthToken) {
      return (RetrieveCandidateList) super.setOauthToken(oauthToken);
    }

    @Override
    public RetrieveCandidateList setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RetrieveCandidateList) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RetrieveCandidateList setQuotaUser(java.lang.String quotaUser) {
      return (RetrieveCandidateList) super.setQuotaUser(quotaUser);
    }

    @Override
    public RetrieveCandidateList setUserIp(java.lang.String userIp) {
      return (RetrieveCandidateList) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long gcId;

    /**

     */
    public java.lang.Long getGcId() {
      return gcId;
    }

    public RetrieveCandidateList setGcId(java.lang.Long gcId) {
      this.gcId = gcId;
      return this;
    }

    @Override
    public RetrieveCandidateList set(String parameterName, Object value) {
      return (RetrieveCandidateList) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "uploadElector".
   *
   * This request holds the parameters needed by the the data server.  After setting any optional
   * parameters, call the {@link UploadElector#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.google.api.services.data.model.Elector}
   * @return the request
   */
  public UploadElector uploadElector(com.google.api.services.data.model.Elector content) throws java.io.IOException {
    UploadElector result = new UploadElector(content);
    initialize(result);
    return result;
  }

  public class UploadElector extends DataRequest<com.google.api.services.data.model.Elector> {

    private static final String REST_PATH = "uploadElector";

    /**
     * Create a request for the method "uploadElector".
     *
     * This request holds the parameters needed by the the data server.  After setting any optional
     * parameters, call the {@link UploadElector#execute()} method to invoke the remote operation. <p>
     * {@link UploadElector#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientR
     * equest)} must be called to initialize this instance immediately after invoking the constructor.
     * </p>
     *
     * @param content the {@link com.google.api.services.data.model.Elector}
     * @since 1.13
     */
    protected UploadElector(com.google.api.services.data.model.Elector content) {
      super(Data.this, "POST", REST_PATH, content, com.google.api.services.data.model.Elector.class);
    }

    @Override
    public UploadElector setAlt(java.lang.String alt) {
      return (UploadElector) super.setAlt(alt);
    }

    @Override
    public UploadElector setFields(java.lang.String fields) {
      return (UploadElector) super.setFields(fields);
    }

    @Override
    public UploadElector setKey(java.lang.String key) {
      return (UploadElector) super.setKey(key);
    }

    @Override
    public UploadElector setOauthToken(java.lang.String oauthToken) {
      return (UploadElector) super.setOauthToken(oauthToken);
    }

    @Override
    public UploadElector setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UploadElector) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UploadElector setQuotaUser(java.lang.String quotaUser) {
      return (UploadElector) super.setQuotaUser(quotaUser);
    }

    @Override
    public UploadElector setUserIp(java.lang.String userIp) {
      return (UploadElector) super.setUserIp(userIp);
    }

    @Override
    public UploadElector set(String parameterName, Object value) {
      return (UploadElector) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "uploadPollData".
   *
   * This request holds the parameters needed by the the data server.  After setting any optional
   * parameters, call the {@link UploadPollData#execute()} method to invoke the remote operation.
   *
   * @param electorId
   * @param content the {@link com.google.api.services.data.model.PollData}
   * @return the request
   */
  public UploadPollData uploadPollData(java.lang.Long electorId, com.google.api.services.data.model.PollData content) throws java.io.IOException {
    UploadPollData result = new UploadPollData(electorId, content);
    initialize(result);
    return result;
  }

  public class UploadPollData extends DataRequest<Void> {

    private static final String REST_PATH = "uploadPollData/{electorId}";

    /**
     * Create a request for the method "uploadPollData".
     *
     * This request holds the parameters needed by the the data server.  After setting any optional
     * parameters, call the {@link UploadPollData#execute()} method to invoke the remote operation.
     * <p> {@link UploadPollData#initialize(com.google.api.client.googleapis.services.AbstractGoogleCl
     * ientRequest)} must be called to initialize this instance immediately after invoking the
     * constructor. </p>
     *
     * @param electorId
     * @param content the {@link com.google.api.services.data.model.PollData}
     * @since 1.13
     */
    protected UploadPollData(java.lang.Long electorId, com.google.api.services.data.model.PollData content) {
      super(Data.this, "POST", REST_PATH, content, Void.class);
      this.electorId = com.google.api.client.util.Preconditions.checkNotNull(electorId, "Required parameter electorId must be specified.");
    }

    @Override
    public UploadPollData setAlt(java.lang.String alt) {
      return (UploadPollData) super.setAlt(alt);
    }

    @Override
    public UploadPollData setFields(java.lang.String fields) {
      return (UploadPollData) super.setFields(fields);
    }

    @Override
    public UploadPollData setKey(java.lang.String key) {
      return (UploadPollData) super.setKey(key);
    }

    @Override
    public UploadPollData setOauthToken(java.lang.String oauthToken) {
      return (UploadPollData) super.setOauthToken(oauthToken);
    }

    @Override
    public UploadPollData setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UploadPollData) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UploadPollData setQuotaUser(java.lang.String quotaUser) {
      return (UploadPollData) super.setQuotaUser(quotaUser);
    }

    @Override
    public UploadPollData setUserIp(java.lang.String userIp) {
      return (UploadPollData) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long electorId;

    /**

     */
    public java.lang.Long getElectorId() {
      return electorId;
    }

    public UploadPollData setElectorId(java.lang.Long electorId) {
      this.electorId = electorId;
      return this;
    }

    @Override
    public UploadPollData set(String parameterName, Object value) {
      return (UploadPollData) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Data}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Data}. */
    @Override
    public Data build() {
      return new Data(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link DataRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setDataRequestInitializer(
        DataRequestInitializer dataRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(dataRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
