/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-05-14 03:07:32 UTC)
 * on 2013-05-16 at 07:43:41 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.data.model;

/**
 * Model definition for Party.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the . For a detailed explanation see:
 * <a href="http://code.google.com/p/google-api-java-client/wiki/Json">http://code.google.com/p/google-api-java-client/wiki/Json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Party extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long partyId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String partyName;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getPartyId() {
    return partyId;
  }

  /**
   * @param partyId partyId or {@code null} for none
   */
  public Party setPartyId(java.lang.Long partyId) {
    this.partyId = partyId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPartyName() {
    return partyName;
  }

  /**
   * @param partyName partyName or {@code null} for none
   */
  public Party setPartyName(java.lang.String partyName) {
    this.partyName = partyName;
    return this;
  }

  @Override
  public Party set(String fieldName, Object value) {
    return (Party) super.set(fieldName, value);
  }

  @Override
  public Party clone() {
    return (Party) super.clone();
  }

}
