/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-05-14 03:07:32 UTC)
 * on 2013-05-16 at 07:43:41 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.data.model;

/**
 * Model definition for PollData.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the . For a detailed explanation see:
 * <a href="http://code.google.com/p/google-api-java-client/wiki/Json">http://code.google.com/p/google-api-java-client/wiki/Json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class PollData extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long electorId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long gcId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long listId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long pdId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime timestamp;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long userId;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getElectorId() {
    return electorId;
  }

  /**
   * @param electorId electorId or {@code null} for none
   */
  public PollData setElectorId(java.lang.Long electorId) {
    this.electorId = electorId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getGcId() {
    return gcId;
  }

  /**
   * @param gcId gcId or {@code null} for none
   */
  public PollData setGcId(java.lang.Long gcId) {
    this.gcId = gcId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getListId() {
    return listId;
  }

  /**
   * @param listId listId or {@code null} for none
   */
  public PollData setListId(java.lang.Long listId) {
    this.listId = listId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getPdId() {
    return pdId;
  }

  /**
   * @param pdId pdId or {@code null} for none
   */
  public PollData setPdId(java.lang.Long pdId) {
    this.pdId = pdId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getTimestamp() {
    return timestamp;
  }

  /**
   * @param timestamp timestamp or {@code null} for none
   */
  public PollData setTimestamp(com.google.api.client.util.DateTime timestamp) {
    this.timestamp = timestamp;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getUserId() {
    return userId;
  }

  /**
   * @param userId userId or {@code null} for none
   */
  public PollData setUserId(java.lang.Long userId) {
    this.userId = userId;
    return this;
  }

  @Override
  public PollData set(String fieldName, Object value) {
    return (PollData) super.set(fieldName, value);
  }

  @Override
  public PollData clone() {
    return (PollData) super.clone();
  }

}
